"""question formulation provenance

Revision ID: 2a69dc52c3ea
Revises: dc269e8f3ce7
Create Date: 2026-09-24 13:24:44.323650

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2a69dc52c3ea"
down_revision: Union[str, Sequence[str], None] = "dc269e8f3ce7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("question_formulations", schema=None) as batch_op:
        batch_op.add_column(sa.Column("ai_provider", sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column("ai_model", sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column("ai_model_version", sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column("prompt_version", sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("question_formulations", schema=None) as batch_op:
        batch_op.drop_column("prompt_version")
        batch_op.drop_column("ai_model_version")
        batch_op.drop_column("ai_model")
        batch_op.drop_column("ai_provider")

    # ### end Alembic commands ###
