"""chapter material, incremental analysis, source review flag

Revision ID: d010fa3a1d03
Revises: 3c4e8750a8c6
Create Date: 2026-09-24 09:40:43.590449

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d010fa3a1d03"
down_revision: Union[str, Sequence[str], None] = "3c4e8750a8c6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("concepts", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "needs_source_review", sa.Boolean(), server_default=sa.false(), nullable=False
            )
        )

    with op.batch_alter_table("curriculum_proposals", schema=None) as batch_op:
        batch_op.add_column(sa.Column("chapter_id", sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column("document_ids", sa.JSON(), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_curriculum_proposals_chapter_id"), ["chapter_id"], unique=False
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_curriculum_proposals_chapter_id_chapters"),
            "chapters",
            ["chapter_id"],
            ["id"],
            ondelete="CASCADE",
        )

    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.add_column(sa.Column("chapter_id", sa.Uuid(), nullable=True))
        batch_op.add_column(sa.Column("analyzed_at", sa.DateTime(timezone=True), nullable=True))
        batch_op.create_index(batch_op.f("ix_documents_chapter_id"), ["chapter_id"], unique=False)
        batch_op.create_foreign_key(
            batch_op.f("fk_documents_chapter_id_chapters"),
            "chapters",
            ["chapter_id"],
            ["id"],
            ondelete="SET NULL",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("fk_documents_chapter_id_chapters"), type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_documents_chapter_id"))
        batch_op.drop_column("analyzed_at")
        batch_op.drop_column("chapter_id")

    with op.batch_alter_table("curriculum_proposals", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_curriculum_proposals_chapter_id_chapters"), type_="foreignkey"
        )
        batch_op.drop_index(batch_op.f("ix_curriculum_proposals_chapter_id"))
        batch_op.drop_column("document_ids")
        batch_op.drop_column("chapter_id")

    with op.batch_alter_table("concepts", schema=None) as batch_op:
        batch_op.drop_column("needs_source_review")

    # ### end Alembic commands ###
