"""xp, consolidation, hints, activity, user preferences

Revision ID: 52ab3371f372
Revises: 21202d6329ba
Create Date: 2026-09-24 19:29:18.133931

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "52ab3371f372"
down_revision: Union[str, Sequence[str], None] = "21202d6329ba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# The CONSOLIDATION session intent and selection mode: these enums are VARCHAR + CHECK, and
# autogenerate doesn't compare CHECK constraints, so their value lists are replaced here.
_INTENTS_BEFORE = ["LEARN", "SCHEDULED_REVIEW", "PRACTICE", "EXAM"]
_INTENTS_AFTER = [*_INTENTS_BEFORE, "CONSOLIDATION"]
_MODES_BEFORE = [
    "DUE",
    "NEW",
    "COURSE_ORDER",
    "RANDOM",
    "WEAK",
    "RECENTLY_FAILED",
    "MARKED_HARD",
    "SELECTED",
]
_MODES_AFTER = [*_MODES_BEFORE, "CONSOLIDATION"]
# (table, column, constraint name suffix, values before, values after)
_CHECKS = [
    ("review_sessions", "intent", "session_intent", _INTENTS_BEFORE, _INTENTS_AFTER),
    ("review_sessions", "selection_mode", "selection_mode", _MODES_BEFORE, _MODES_AFTER),
    ("answers", "intent", "answer_intent", _INTENTS_BEFORE, _INTENTS_AFTER),
    ("reviews", "intent", "review_intent", _INTENTS_BEFORE, _INTENTS_AFTER),
]


def _replace_checks(after: bool) -> None:
    for table, column, name, before_values, after_values in _CHECKS:
        values = after_values if after else before_values
        listed = ", ".join(f"'{v}'" for v in values)
        with op.batch_alter_table(table, schema=None) as batch_op:
            batch_op.drop_constraint(batch_op.f(f"ck_{table}_{name}"), type_="check")
            batch_op.create_check_constraint(
                batch_op.f(f"ck_{table}_{name}"), sa.text(f"{column} IN ({listed})")
            )


def upgrade() -> None:
    """Upgrade schema."""
    _replace_checks(after=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "daily_activity",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("xp", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_daily_activity_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_daily_activity")),
        sa.UniqueConstraint("user_id", "day", name=op.f("uq_daily_activity_user_id_day")),
    )
    with op.batch_alter_table("daily_activity", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_daily_activity_user_id"), ["user_id"], unique=False)

    op.create_table(
        "item_success_counters",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("course_id", sa.Uuid(), nullable=False),
        sa.Column("learning_item_id", sa.Uuid(), nullable=False),
        sa.Column("successful_answers", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("fk_item_success_counters_course_id_courses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["learning_item_id"],
            ["learning_items.id"],
            name=op.f("fk_item_success_counters_learning_item_id_learning_items"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_item_success_counters_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_item_success_counters")),
        sa.UniqueConstraint(
            "learning_item_id", name=op.f("uq_item_success_counters_learning_item_id")
        ),
    )
    with op.batch_alter_table("item_success_counters", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_item_success_counters_course_id"), ["course_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_item_success_counters_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "hint_reveals",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("course_id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("slot", sa.Integer(), nullable=False),
        sa.Column("learning_item_id", sa.Uuid(), nullable=False),
        sa.Column("question_formulation_id", sa.Uuid(), nullable=False),
        sa.Column("text", sa.String(length=300), nullable=False),
        sa.Column("revealed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("fk_hint_reveals_course_id_courses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["learning_item_id"],
            ["learning_items.id"],
            name=op.f("fk_hint_reveals_learning_item_id_learning_items"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["question_formulation_id"],
            ["question_formulations.id"],
            name=op.f("fk_hint_reveals_question_formulation_id_question_formulations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["review_sessions.id"],
            name=op.f("fk_hint_reveals_session_id_review_sessions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_hint_reveals_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_hint_reveals")),
        sa.UniqueConstraint("session_id", "slot", name=op.f("uq_hint_reveals_session_id_slot")),
    )
    with op.batch_alter_table("hint_reveals", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_hint_reveals_course_id"), ["course_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_hint_reveals_learning_item_id"), ["learning_item_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_hint_reveals_session_id"), ["session_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_hint_reveals_user_id"), ["user_id"], unique=False)

    op.create_table(
        "xp_awards",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("course_id", sa.Uuid(), nullable=False),
        sa.Column("learning_item_id", sa.Uuid(), nullable=False),
        sa.Column("answer_id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column(
            "reason",
            sa.Enum(
                "INITIAL",
                "SCHEDULED_REVIEW",
                name="xp_reason",
                native_enum=False,
                create_constraint=True,
                length=30,
            ),
            nullable=False,
        ),
        sa.Column("occasion_key", sa.String(length=80), nullable=False),
        sa.Column("correct", sa.Boolean(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=True),
        sa.Column("base_xp", sa.Integer(), nullable=False),
        sa.Column("hint_used", sa.Boolean(), server_default=sa.false(), nullable=False),
        sa.Column("xp", sa.Integer(), nullable=False),
        sa.Column("policy_version", sa.String(length=20), nullable=False),
        sa.Column("awarded_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["answer_id"],
            ["answers.id"],
            name=op.f("fk_xp_awards_answer_id_answers"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("fk_xp_awards_course_id_courses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["learning_item_id"],
            ["learning_items.id"],
            name=op.f("fk_xp_awards_learning_item_id_learning_items"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["review_sessions.id"],
            name=op.f("fk_xp_awards_session_id_review_sessions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_xp_awards_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_xp_awards")),
        sa.UniqueConstraint("answer_id", name=op.f("uq_xp_awards_answer_id")),
        sa.UniqueConstraint(
            "learning_item_id",
            "occasion_key",
            name=op.f("uq_xp_awards_learning_item_id_occasion_key"),
        ),
        sa.UniqueConstraint(
            "learning_item_id", "ordinal", name=op.f("uq_xp_awards_learning_item_id_ordinal")
        ),
    )
    with op.batch_alter_table("xp_awards", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_xp_awards_course_id"), ["course_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_xp_awards_learning_item_id"), ["learning_item_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_xp_awards_session_id"), ["session_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_xp_awards_user_id"), ["user_id"], unique=False)
        batch_op.create_index(
            "ix_xp_awards_user_id_awarded_at", ["user_id", "awarded_at"], unique=False
        )

    with op.batch_alter_table("answers", schema=None) as batch_op:
        batch_op.add_column(sa.Column("finalized_at", sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column("consolidation_round", sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column("hint_used", sa.Boolean(), server_default=sa.false(), nullable=False)
        )
        batch_op.create_index(
            "ix_answers_course_id_finalized_at", ["course_id", "finalized_at"], unique=False
        )
        batch_op.create_index(
            "ix_answers_user_id_finalized_at", ["user_id", "finalized_at"], unique=False
        )

    with op.batch_alter_table("question_formulations", schema=None) as batch_op:
        batch_op.add_column(sa.Column("hint", sa.String(length=300), nullable=True))

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("timezone", sa.String(length=64), server_default="UTC", nullable=False)
        )
        batch_op.add_column(
            sa.Column("daily_goal", sa.Integer(), server_default="20", nullable=False)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("daily_goal")
        batch_op.drop_column("timezone")

    with op.batch_alter_table("question_formulations", schema=None) as batch_op:
        batch_op.drop_column("hint")

    with op.batch_alter_table("answers", schema=None) as batch_op:
        batch_op.drop_index("ix_answers_user_id_finalized_at")
        batch_op.drop_index("ix_answers_course_id_finalized_at")
        batch_op.drop_column("hint_used")
        batch_op.drop_column("consolidation_round")
        batch_op.drop_column("finalized_at")

    with op.batch_alter_table("xp_awards", schema=None) as batch_op:
        batch_op.drop_index("ix_xp_awards_user_id_awarded_at")
        batch_op.drop_index(batch_op.f("ix_xp_awards_user_id"))
        batch_op.drop_index(batch_op.f("ix_xp_awards_session_id"))
        batch_op.drop_index(batch_op.f("ix_xp_awards_learning_item_id"))
        batch_op.drop_index(batch_op.f("ix_xp_awards_course_id"))

    op.drop_table("xp_awards")
    with op.batch_alter_table("hint_reveals", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_hint_reveals_user_id"))
        batch_op.drop_index(batch_op.f("ix_hint_reveals_session_id"))
        batch_op.drop_index(batch_op.f("ix_hint_reveals_learning_item_id"))
        batch_op.drop_index(batch_op.f("ix_hint_reveals_course_id"))

    op.drop_table("hint_reveals")
    with op.batch_alter_table("item_success_counters", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_item_success_counters_user_id"))
        batch_op.drop_index(batch_op.f("ix_item_success_counters_course_id"))

    op.drop_table("item_success_counters")
    with op.batch_alter_table("daily_activity", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_daily_activity_user_id"))

    op.drop_table("daily_activity")
    # ### end Alembic commands ###
    # Consolidation history can't be expressed in the older schema: it goes with the downgrade.
    op.execute(sa.text("DELETE FROM reviews WHERE intent = 'CONSOLIDATION'"))
    op.execute(sa.text("DELETE FROM answers WHERE intent = 'CONSOLIDATION'"))
    op.execute(sa.text("DELETE FROM review_sessions WHERE intent = 'CONSOLIDATION'"))
    _replace_checks(after=False)
