"""curriculum proposals, concept sources, concept order

Revision ID: 3c4e8750a8c6
Revises: e4ade709374c
Create Date: 2026-09-24 09:05:39.502843

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3c4e8750a8c6"
down_revision: Union[str, Sequence[str], None] = "e4ade709374c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "curriculum_proposals",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("course_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "GENERATING",
                "READY",
                "INSUFFICIENT_CONTEXT",
                "FAILED",
                "APPLIED",
                name="curriculum_proposal_status",
                native_enum=False,
                create_constraint=True,
                length=30,
            ),
            nullable=False,
        ),
        sa.Column("error_message", sa.String(length=500), nullable=True),
        sa.Column("content", sa.JSON(), nullable=True),
        sa.Column("passages_used", sa.Integer(), nullable=False),
        sa.Column("passages_total", sa.Integer(), nullable=False),
        sa.Column("dropped_concepts", sa.Integer(), nullable=False),
        sa.Column("ai_provider", sa.String(length=50), nullable=True),
        sa.Column("ai_model", sa.String(length=200), nullable=True),
        sa.Column("ai_model_version", sa.String(length=200), nullable=True),
        sa.Column("prompt_version", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("applied_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("fk_curriculum_proposals_course_id_courses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_curriculum_proposals")),
    )
    with op.batch_alter_table("curriculum_proposals", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_curriculum_proposals_course_id"), ["course_id"], unique=False
        )

    op.create_table(
        "concept_sources",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("concept_id", sa.Uuid(), nullable=False),
        sa.Column("chunk_id", sa.Uuid(), nullable=False),
        sa.Column("course_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["chunk_id"],
            ["document_chunks.id"],
            name=op.f("fk_concept_sources_chunk_id_document_chunks"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["concept_id"],
            ["concepts.id"],
            name=op.f("fk_concept_sources_concept_id_concepts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("fk_concept_sources_course_id_courses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_concept_sources")),
        sa.UniqueConstraint(
            "concept_id", "chunk_id", name=op.f("uq_concept_sources_concept_id_chunk_id")
        ),
    )
    with op.batch_alter_table("concept_sources", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_concept_sources_chunk_id"), ["chunk_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_concept_sources_concept_id"), ["concept_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_concept_sources_course_id"), ["course_id"], unique=False
        )

    with op.batch_alter_table("concepts", schema=None) as batch_op:
        batch_op.add_column(sa.Column("order", sa.Integer(), server_default="0", nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("concepts", schema=None) as batch_op:
        batch_op.drop_column("order")

    with op.batch_alter_table("concept_sources", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_concept_sources_course_id"))
        batch_op.drop_index(batch_op.f("ix_concept_sources_concept_id"))
        batch_op.drop_index(batch_op.f("ix_concept_sources_chunk_id"))

    op.drop_table("concept_sources")
    with op.batch_alter_table("curriculum_proposals", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_curriculum_proposals_course_id"))

    op.drop_table("curriculum_proposals")
    # ### end Alembic commands ###
