"""pause flags on courses chapters topics

Revision ID: 8c813501a013
Revises: a83a753e87c1
Create Date: 2026-09-23 22:38:49.650102

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8c813501a013"
down_revision: Union[str, Sequence[str], None] = "a83a753e87c1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("chapters", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("paused", sa.Boolean(), server_default=sa.false(), nullable=False)
        )

    with op.batch_alter_table("courses", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("paused", sa.Boolean(), server_default=sa.false(), nullable=False)
        )

    with op.batch_alter_table("topics", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("paused", sa.Boolean(), server_default=sa.false(), nullable=False)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("topics", schema=None) as batch_op:
        batch_op.drop_column("paused")

    with op.batch_alter_table("courses", schema=None) as batch_op:
        batch_op.drop_column("paused")

    with op.batch_alter_table("chapters", schema=None) as batch_op:
        batch_op.drop_column("paused")

    # ### end Alembic commands ###
