"""review sessions, answers, evaluations, review history

Revision ID: dc269e8f3ce7
Revises: 8cfd6e07b917
Create Date: 2026-09-24 10:43:32.221552

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dc269e8f3ce7"
down_revision: Union[str, Sequence[str], None] = "8cfd6e07b917"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "review_sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("course_id", sa.Uuid(), nullable=False),
        sa.Column(
            "intent",
            sa.Enum(
                "LEARN",
                "SCHEDULED_REVIEW",
                "PRACTICE",
                "EXAM",
                name="session_intent",
                native_enum=False,
                create_constraint=True,
                length=30,
            ),
            nullable=False,
        ),
        sa.Column(
            "selection_mode",
            sa.Enum(
                "DUE",
                "NEW",
                "COURSE_ORDER",
                "RANDOM",
                "WEAK",
                "RECENTLY_FAILED",
                "MARKED_HARD",
                "SELECTED",
                name="selection_mode",
                native_enum=False,
                create_constraint=True,
                length=30,
            ),
            nullable=False,
        ),
        sa.Column("affects_schedule", sa.Boolean(), nullable=False),
        sa.Column("chapter_id", sa.Uuid(), nullable=True),
        sa.Column("topic_id", sa.Uuid(), nullable=True),
        sa.Column("concept_ids", sa.JSON(), nullable=True),
        sa.Column("item_ids", sa.JSON(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("fk_review_sessions_course_id_courses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_review_sessions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review_sessions")),
    )
    with op.batch_alter_table("review_sessions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_review_sessions_course_id"), ["course_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_review_sessions_user_id"), ["user_id"], unique=False)

    op.create_table(
        "answers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("course_id", sa.Uuid(), nullable=False),
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("learning_item_id", sa.Uuid(), nullable=False),
        sa.Column("question_formulation_id", sa.Uuid(), nullable=False),
        sa.Column(
            "intent",
            sa.Enum(
                "LEARN",
                "SCHEDULED_REVIEW",
                "PRACTICE",
                "EXAM",
                name="answer_intent",
                native_enum=False,
                create_constraint=True,
                length=30,
            ),
            nullable=False,
        ),
        sa.Column(
            "method",
            sa.Enum(
                "TEXT",
                "VOICE",
                name="answer_method",
                native_enum=False,
                create_constraint=True,
                length=10,
            ),
            nullable=False,
        ),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column(
            "resolved_outcome",
            sa.Enum(
                "AGAIN",
                "HARD",
                "GOOD",
                "EASY",
                name="resolved_outcome",
                native_enum=False,
                create_constraint=True,
                length=10,
            ),
            nullable=True,
        ),
        sa.Column("resolver_version", sa.String(length=50), nullable=True),
        sa.Column(
            "override_outcome",
            sa.Enum(
                "AGAIN",
                "HARD",
                "GOOD",
                "EASY",
                name="override_outcome",
                native_enum=False,
                create_constraint=True,
                length=10,
            ),
            nullable=True,
        ),
        sa.Column("override_note", sa.String(length=500), nullable=True),
        sa.Column("overridden_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "final_outcome",
            sa.Enum(
                "AGAIN",
                "HARD",
                "GOOD",
                "EASY",
                name="final_outcome",
                native_enum=False,
                create_constraint=True,
                length=10,
            ),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("fk_answers_course_id_courses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["learning_item_id"],
            ["learning_items.id"],
            name=op.f("fk_answers_learning_item_id_learning_items"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["question_formulation_id"],
            ["question_formulations.id"],
            name=op.f("fk_answers_question_formulation_id_question_formulations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["review_sessions.id"],
            name=op.f("fk_answers_session_id_review_sessions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_answers_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_answers")),
    )
    with op.batch_alter_table("answers", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_answers_course_id"), ["course_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_answers_learning_item_id"), ["learning_item_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_answers_session_id"), ["session_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_answers_user_id"), ["user_id"], unique=False)

    op.create_table(
        "evaluations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("answer_id", sa.Uuid(), nullable=False),
        sa.Column("course_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "COMPLETED",
                "FAILED",
                "NOT_CONFIGURED",
                name="evaluation_status",
                native_enum=False,
                create_constraint=True,
                length=30,
            ),
            nullable=False,
        ),
        sa.Column("error_message", sa.String(length=500), nullable=True),
        sa.Column(
            "classification",
            sa.Enum(
                "CORRECT",
                "PARTIALLY_CORRECT",
                "MISCONCEPTION",
                "WRONG",
                "UNCERTAIN",
                name="evaluation_classification",
                native_enum=False,
                create_constraint=True,
                length=30,
            ),
            nullable=True,
        ),
        sa.Column("correctness", sa.Float(), nullable=True),
        sa.Column("completeness", sa.Float(), nullable=True),
        sa.Column("conceptual_understanding", sa.Float(), nullable=True),
        sa.Column("precision", sa.Float(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("correct_points", sa.JSON(), nullable=False),
        sa.Column("missing_points", sa.JSON(), nullable=False),
        sa.Column("misconceptions", sa.JSON(), nullable=False),
        sa.Column("source_corrections", sa.JSON(), nullable=False),
        sa.Column("context_sufficient", sa.Boolean(), nullable=True),
        sa.Column("feedback", sa.Text(), nullable=False),
        sa.Column("ai_provider", sa.String(length=50), nullable=True),
        sa.Column("ai_model", sa.String(length=200), nullable=True),
        sa.Column("ai_model_version", sa.String(length=200), nullable=True),
        sa.Column("prompt_version", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["answer_id"],
            ["answers.id"],
            name=op.f("fk_evaluations_answer_id_answers"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("fk_evaluations_course_id_courses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_evaluations")),
    )
    with op.batch_alter_table("evaluations", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_evaluations_answer_id"), ["answer_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_evaluations_course_id"), ["course_id"], unique=False)

    op.create_table(
        "reviews",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("course_id", sa.Uuid(), nullable=False),
        sa.Column("learning_item_id", sa.Uuid(), nullable=False),
        sa.Column("answer_id", sa.Uuid(), nullable=False),
        sa.Column(
            "intent",
            sa.Enum(
                "LEARN",
                "SCHEDULED_REVIEW",
                "PRACTICE",
                "EXAM",
                name="review_intent",
                native_enum=False,
                create_constraint=True,
                length=30,
            ),
            nullable=False,
        ),
        sa.Column(
            "outcome",
            sa.Enum(
                "AGAIN",
                "HARD",
                "GOOD",
                "EASY",
                name="review_outcome",
                native_enum=False,
                create_constraint=True,
                length=10,
            ),
            nullable=False,
        ),
        sa.Column(
            "previous_state",
            sa.Enum(
                "NEW",
                "LEARNING",
                "REVIEW",
                "RELEARNING",
                "MASTERED",
                name="previous_state",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("previous_level", sa.Integer(), nullable=False),
        sa.Column("previous_due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "next_state",
            sa.Enum(
                "NEW",
                "LEARNING",
                "REVIEW",
                "RELEARNING",
                "MASTERED",
                name="next_state",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("next_level", sa.Integer(), nullable=False),
        sa.Column("next_due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("lateness_seconds", sa.Integer(), nullable=False),
        sa.Column("scheduling_policy", sa.String(length=50), nullable=False),
        sa.Column("scheduling_policy_version", sa.String(length=20), nullable=False),
        sa.Column("previous_snapshot", sa.JSON(), nullable=False),
        sa.Column("supersedes_review_id", sa.Uuid(), nullable=True),
        sa.Column("superseded", sa.Boolean(), server_default=sa.false(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["answer_id"],
            ["answers.id"],
            name=op.f("fk_reviews_answer_id_answers"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("fk_reviews_course_id_courses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["learning_item_id"],
            ["learning_items.id"],
            name=op.f("fk_reviews_learning_item_id_learning_items"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_review_id"],
            ["reviews.id"],
            name=op.f("fk_reviews_supersedes_review_id_reviews"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reviews")),
    )
    with op.batch_alter_table("reviews", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_reviews_answer_id"), ["answer_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_reviews_course_id"), ["course_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_reviews_learning_item_id"), ["learning_item_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("reviews", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_reviews_learning_item_id"))
        batch_op.drop_index(batch_op.f("ix_reviews_course_id"))
        batch_op.drop_index(batch_op.f("ix_reviews_answer_id"))

    op.drop_table("reviews")
    with op.batch_alter_table("evaluations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_evaluations_course_id"))
        batch_op.drop_index(batch_op.f("ix_evaluations_answer_id"))

    op.drop_table("evaluations")
    with op.batch_alter_table("answers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_answers_user_id"))
        batch_op.drop_index(batch_op.f("ix_answers_session_id"))
        batch_op.drop_index(batch_op.f("ix_answers_learning_item_id"))
        batch_op.drop_index(batch_op.f("ix_answers_course_id"))

    op.drop_table("answers")
    with op.batch_alter_table("review_sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_review_sessions_user_id"))
        batch_op.drop_index(batch_op.f("ix_review_sessions_course_id"))

    op.drop_table("review_sessions")
    # ### end Alembic commands ###
