"""learning items, questions, sources, review states

Revision ID: 8cfd6e07b917
Revises: d010fa3a1d03
Create Date: 2026-09-24 10:32:14.583193

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8cfd6e07b917"
down_revision: Union[str, Sequence[str], None] = "d010fa3a1d03"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "learning_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("concept_id", sa.Uuid(), nullable=False),
        sa.Column("topic_id", sa.Uuid(), nullable=False),
        sa.Column("chapter_id", sa.Uuid(), nullable=False),
        sa.Column("course_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("objective", sa.String(length=2000), nullable=False),
        sa.Column("expected_knowledge", sa.Text(), nullable=False),
        sa.Column("essential_points", sa.JSON(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "CORE_TRAINABLE",
                "SUPPORTING_TRAINABLE",
                "COMMON_TRAP",
                "INFORMATIONAL",
                "REFERENCE",
                "OPTIONAL_EXTENSION",
                name="learning_item_role",
                native_enum=False,
                create_constraint=True,
                length=30,
            ),
            nullable=False,
        ),
        sa.Column("in_training", sa.Boolean(), server_default=sa.false(), nullable=False),
        sa.Column("difficulty", sa.Integer(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("paused", sa.Boolean(), server_default=sa.false(), nullable=False),
        sa.Column("ai_provider", sa.String(length=50), nullable=True),
        sa.Column("ai_model", sa.String(length=200), nullable=True),
        sa.Column("ai_model_version", sa.String(length=200), nullable=True),
        sa.Column("prompt_version", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["chapter_id"],
            ["chapters.id"],
            name=op.f("fk_learning_items_chapter_id_chapters"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["concept_id"],
            ["concepts.id"],
            name=op.f("fk_learning_items_concept_id_concepts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("fk_learning_items_course_id_courses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["topic_id"],
            ["topics.id"],
            name=op.f("fk_learning_items_topic_id_topics"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_learning_items")),
    )
    with op.batch_alter_table("learning_items", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_learning_items_chapter_id"), ["chapter_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_learning_items_concept_id"), ["concept_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_learning_items_course_id"), ["course_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_learning_items_topic_id"), ["topic_id"], unique=False)

    op.create_table(
        "learning_item_sources",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("learning_item_id", sa.Uuid(), nullable=False),
        sa.Column("chunk_id", sa.Uuid(), nullable=False),
        sa.Column("course_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["chunk_id"],
            ["document_chunks.id"],
            name=op.f("fk_learning_item_sources_chunk_id_document_chunks"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("fk_learning_item_sources_course_id_courses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["learning_item_id"],
            ["learning_items.id"],
            name=op.f("fk_learning_item_sources_learning_item_id_learning_items"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_learning_item_sources")),
        sa.UniqueConstraint(
            "learning_item_id",
            "chunk_id",
            name=op.f("uq_learning_item_sources_learning_item_id_chunk_id"),
        ),
    )
    with op.batch_alter_table("learning_item_sources", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_learning_item_sources_chunk_id"), ["chunk_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_learning_item_sources_course_id"), ["course_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_learning_item_sources_learning_item_id"),
            ["learning_item_id"],
            unique=False,
        )

    op.create_table(
        "question_formulations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("learning_item_id", sa.Uuid(), nullable=False),
        sa.Column("course_id", sa.Uuid(), nullable=False),
        sa.Column(
            "question_type",
            sa.Enum(
                "RECALL",
                "DEFINITION",
                "EXPLANATION",
                "WHY_HOW",
                "COMPARISON",
                "CAUSE_EFFECT",
                "APPLICATION",
                "SCENARIO",
                "CALCULATION",
                "CLASSIFICATION",
                "TEACH_BACK",
                "ORAL_EXAM",
                "COUNTEREXAMPLE",
                "EDGE_CASE",
                "CONCEPT_CONNECTION",
                name="question_type",
                native_enum=False,
                create_constraint=True,
                length=30,
            ),
            nullable=False,
        ),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("times_asked", sa.Integer(), nullable=False),
        sa.Column("last_asked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("fk_question_formulations_course_id_courses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["learning_item_id"],
            ["learning_items.id"],
            name=op.f("fk_question_formulations_learning_item_id_learning_items"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_question_formulations")),
    )
    with op.batch_alter_table("question_formulations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_question_formulations_course_id"), ["course_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_question_formulations_learning_item_id"),
            ["learning_item_id"],
            unique=False,
        )

    op.create_table(
        "review_states",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("learning_item_id", sa.Uuid(), nullable=False),
        sa.Column("course_id", sa.Uuid(), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "NEW",
                "LEARNING",
                "REVIEW",
                "RELEARNING",
                "MASTERED",
                name="memory_state",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("interval_seconds", sa.Integer(), nullable=True),
        sa.Column("due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("review_count", sa.Integer(), nullable=False),
        sa.Column("successful_review_count", sa.Integer(), nullable=False),
        sa.Column("failed_review_count", sa.Integer(), nullable=False),
        sa.Column("lapse_count", sa.Integer(), nullable=False),
        sa.Column("hard_count", sa.Integer(), nullable=False),
        sa.Column("marked_hard", sa.Boolean(), server_default=sa.false(), nullable=False),
        sa.Column("paused_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("scheduling_policy", sa.String(length=50), nullable=False),
        sa.Column("scheduling_policy_version", sa.String(length=20), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
            name=op.f("fk_review_states_course_id_courses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["learning_item_id"],
            ["learning_items.id"],
            name=op.f("fk_review_states_learning_item_id_learning_items"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review_states")),
        sa.UniqueConstraint("learning_item_id", name=op.f("uq_review_states_learning_item_id")),
    )
    with op.batch_alter_table("review_states", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_review_states_course_id"), ["course_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_review_states_due_at"), ["due_at"], unique=False)

    with op.batch_alter_table("concepts", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "item_generation_status",
                sa.Enum(
                    "NONE",
                    "GENERATING",
                    "READY",
                    "INSUFFICIENT_CONTEXT",
                    "FAILED",
                    name="item_generation_status",
                    native_enum=False,
                    create_constraint=True,
                    length=30,
                ),
                server_default="NONE",
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column("item_generation_error", sa.String(length=500), nullable=True)
        )
        batch_op.add_column(
            sa.Column("item_generation_started_at", sa.DateTime(timezone=True), nullable=True)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("concepts", schema=None) as batch_op:
        batch_op.drop_column("item_generation_started_at")
        batch_op.drop_column("item_generation_error")
        # The CHECK constraint must go first: SQLite's batch rebuild would otherwise keep a
        # constraint on a column that no longer exists.
        batch_op.drop_constraint(batch_op.f("ck_concepts_item_generation_status"), type_="check")
        batch_op.drop_column("item_generation_status")

    with op.batch_alter_table("review_states", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_review_states_due_at"))
        batch_op.drop_index(batch_op.f("ix_review_states_course_id"))

    op.drop_table("review_states")
    with op.batch_alter_table("question_formulations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_question_formulations_learning_item_id"))
        batch_op.drop_index(batch_op.f("ix_question_formulations_course_id"))

    op.drop_table("question_formulations")
    with op.batch_alter_table("learning_item_sources", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_learning_item_sources_learning_item_id"))
        batch_op.drop_index(batch_op.f("ix_learning_item_sources_course_id"))
        batch_op.drop_index(batch_op.f("ix_learning_item_sources_chunk_id"))

    op.drop_table("learning_item_sources")
    with op.batch_alter_table("learning_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_learning_items_topic_id"))
        batch_op.drop_index(batch_op.f("ix_learning_items_course_id"))
        batch_op.drop_index(batch_op.f("ix_learning_items_concept_id"))
        batch_op.drop_index(batch_op.f("ix_learning_items_chapter_id"))

    op.drop_table("learning_items")
    # ### end Alembic commands ###
