"""document purpose, import notice, chunk page_end

Revision ID: 21202d6329ba
Revises: 2a69dc52c3ea
Create Date: 2026-09-24 17:55:05.168520

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "21202d6329ba"
down_revision: Union[str, Sequence[str], None] = "2a69dc52c3ea"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("document_chunks", schema=None) as batch_op:
        batch_op.add_column(sa.Column("page_end", sa.Integer(), nullable=True))

    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "purpose",
                sa.Enum(
                    "MATERIAL",
                    "QUESTION_BANK",
                    name="document_purpose",
                    native_enum=False,
                    create_constraint=True,
                    length=20,
                ),
                server_default="MATERIAL",
                nullable=False,
            )
        )
        batch_op.add_column(sa.Column("import_notice", sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("documents", schema=None) as batch_op:
        batch_op.drop_column("import_notice")
        batch_op.drop_constraint(batch_op.f("ck_documents_document_purpose"), type_="check")
        batch_op.drop_column("purpose")

    with op.batch_alter_table("document_chunks", schema=None) as batch_op:
        batch_op.drop_column("page_end")

    # ### end Alembic commands ###
